<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InventoryItem;

class InventoryItemSeeder extends Seeder
{
    public function run(): void
    {
        $inventoryItems = [
            // Baking Ingredients
            [
                'item_name' => 'All-Purpose Flour',
                'qr_code' => 'APF001',
                'current_quantity' => 500.0,
                'unit_of_measurement' => 'pounds',
                'cost_per_unit' => 1.25,
                'supplier_name' => 'King Arthur Baking',
                'supplier_contact' => 'orders@kingarthurbaking.com',
                'minimum_stock_level' => 50.0,
                'maximum_stock_level' => 1000.0,
                'shelf_life_days' => 365,
                'storage_requirements' => 'Dry Storage A1, cool and dry',
                'category' => 'baking_ingredients',
                'status' => 'in_stock',
            ],
            [
                'item_name' => 'Granulated Sugar',
                'qr_code' => 'GS001',
                'current_quantity' => 300.0,
                'unit_of_measurement' => 'pounds',
                'cost_per_unit' => 0.85,
                'supplier_name' => 'C&H Sugar',
                'supplier_contact' => 'wholesale@chsugar.com',
                'minimum_stock_level' => 40.0,
                'maximum_stock_level' => 600.0,
                'shelf_life_days' => 730,
                'storage_requirements' => 'Dry Storage A2, airtight container',
                'category' => 'baking_ingredients',
                'status' => 'in_stock',
            ],
            [
                'item_name' => 'Unsalted Butter',
                'qr_code' => 'UB001',
                'current_quantity' => 80.0,
                'unit_of_measurement' => 'pounds',
                'cost_per_unit' => 6.50,
                'supplier_name' => 'Kerrygold',
                'supplier_contact' => 'wholesale@kerrygold.com',
                'minimum_stock_level' => 20.0,
                'maximum_stock_level' => 150.0,
                'shelf_life_days' => 45,
                'storage_requirements' => 'Walk-in Freezer B1, below 0°F',
                'category' => 'dairy',
                'status' => 'in_stock',
            ],
            [
                'item_name' => 'Large Eggs',
                'qr_code' => 'LE001',
                'current_quantity' => 60.0,
                'unit_of_measurement' => 'dozen',
                'cost_per_unit' => 3.25,
                'supplier_name' => 'Local Farm Co-op',
                'supplier_contact' => 'orders@localfarmcoop.com',
                'minimum_stock_level' => 15.0,
                'maximum_stock_level' => 120.0,
                'shelf_life_days' => 21,
                'storage_requirements' => 'Walk-in Cooler C1, 32-40°F',
                'category' => 'dairy',
                'status' => 'in_stock',
            ],
            [
                'item_name' => 'Vanilla Extract',
                'qr_code' => 'VE001',
                'current_quantity' => 32.0,
                'unit_of_measurement' => 'fluid_ounces',
                'cost_per_unit' => 2.85,
                'supplier_name' => 'Nielsen-Massey',
                'supplier_contact' => 'orders@nielsenmassey.com',
                'minimum_stock_level' => 8.0,
                'maximum_stock_level' => 64.0,
                'shelf_life_days' => 1095,
                'storage_requirements' => 'Dry Storage B3, room temperature',
                'category' => 'flavoring',
                'status' => 'in_stock',
            ],
            [
                'item_name' => 'Semi-Sweet Chocolate Chips',
                'qr_code' => 'SCC001',
                'current_quantity' => 120.0,
                'unit_of_measurement' => 'pounds',
                'cost_per_unit' => 8.95,
                'supplier_name' => 'Callebaut',
                'supplier_contact' => 'wholesale@callebaut.com',
                'minimum_stock_level' => 25.0,
                'maximum_stock_level' => 250.0,
                'shelf_life_days' => 545,
                'storage_requirements' => 'Dry Storage C2, cool and dry',
                'category' => 'chocolate',
                'status' => 'in_stock',
            ],
            [
                'item_name' => 'Cream Cheese',
                'qr_code' => 'CC001',
                'current_quantity' => 40.0,
                'unit_of_measurement' => 'pounds',
                'cost_per_unit' => 4.25,
                'supplier_name' => 'Kraft Heinz',
                'supplier_contact' => 'foodservice@kraftheinz.com',
                'minimum_stock_level' => 10.0,
                'maximum_stock_level' => 80.0,
                'shelf_life_days' => 60,
                'storage_requirements' => 'Walk-in Cooler C2, 32-40°F',
                'category' => 'dairy',
                'status' => 'in_stock',
            ],
            [
                'item_name' => 'Fresh Strawberries',
                'qr_code' => 'FS001',
                'current_quantity' => 25.0,
                'unit_of_measurement' => 'pounds',
                'cost_per_unit' => 4.50,
                'supplier_name' => 'Fresh Fruit Distributors',
                'supplier_contact' => 'orders@freshfruitdist.com',
                'minimum_stock_level' => 5.0,
                'maximum_stock_level' => 50.0,
                'shelf_life_days' => 5,
                'storage_requirements' => 'Walk-in Cooler A1, 32-36°F, high humidity',
                'category' => 'fruit',
                'status' => 'low_stock',
            ],
            [
                'item_name' => 'Baking Powder',
                'qr_code' => 'BP001',
                'current_quantity' => 15.0,
                'unit_of_measurement' => 'pounds',
                'cost_per_unit' => 5.75,
                'supplier_name' => 'Clabber Girl',
                'supplier_contact' => 'commercial@clabbergirl.com',
                'minimum_stock_level' => 3.0,
                'maximum_stock_level' => 30.0,
                'shelf_life_days' => 545,
                'storage_requirements' => 'Dry Storage B1, sealed container',
                'category' => 'leavening',
                'status' => 'in_stock',
            ],
            [
                'item_name' => 'Powdered Sugar',
                'qr_code' => 'PS001',
                'current_quantity' => 75.0,
                'unit_of_measurement' => 'pounds',
                'cost_per_unit' => 1.95,
                'supplier_name' => 'Domino Sugar',
                'supplier_contact' => 'wholesale@dominosugar.com',
                'minimum_stock_level' => 15.0,
                'maximum_stock_level' => 150.0,
                'shelf_life_days' => 730,
                'storage_requirements' => 'Dry Storage A3, airtight container',
                'category' => 'baking_ingredients',
                'status' => 'in_stock',
            ],

            // Low Stock Items for Testing
            [
                'item_name' => 'Brown Sugar',
                'qr_code' => 'BS001',
                'current_quantity' => 8.0,
                'unit_of_measurement' => 'pounds',
                'cost_per_unit' => 1.15,
                'supplier_name' => 'C&H Sugar',
                'supplier_contact' => 'wholesale@chsugar.com',
                'minimum_stock_level' => 20.0,
                'maximum_stock_level' => 100.0,
                'shelf_life_days' => 365,
                'storage_requirements' => 'Dry Storage A2, sealed container',
                'category' => 'baking_ingredients',
                'status' => 'low_stock',
            ],
            [
                'item_name' => 'Heavy Cream',
                'qr_code' => 'HC001',
                'current_quantity' => 3.0,
                'unit_of_measurement' => 'quarts',
                'cost_per_unit' => 3.85,
                'supplier_name' => 'Organic Valley',
                'supplier_contact' => 'wholesale@organicvalley.com',
                'minimum_stock_level' => 12.0,
                'maximum_stock_level' => 48.0,
                'shelf_life_days' => 10,
                'storage_requirements' => 'Walk-in Cooler C3, 32-38°F',
                'category' => 'dairy',
                'status' => 'low_stock',
            ]
        ];

        foreach ($inventoryItems as $itemData) {
            InventoryItem::create($itemData);
        }

        $this->command->info('Created ' . count($inventoryItems) . ' inventory items');
    }
}